# Generated by Django 5.2.10 on 2026-03-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Angajat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nume", models.CharField(max_length=100)),
                ("prenume", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefon", models.CharField(blank=True, max_length=20)),
                ("functie", models.CharField(max_length=100)),
                ("departament", models.CharField(blank=True, max_length=100)),
                ("data_angajare", models.DateField()),
                ("activ", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Angajat",
                "verbose_name_plural": "Angajati",
                "ordering": ["nume"],
            },
        ),
    ]
