# Generated by Django 5.2.10 on 2026-03-10 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("angajati", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nume", models.CharField(max_length=200)),
                (
                    "tip",
                    models.CharField(
                        choices=[
                            ("contract", "Contract"),
                            ("revizie", "Revizie medicală"),
                            ("autorizatie", "Autorizație"),
                            ("alt", "Altul"),
                        ],
                        max_length=50,
                    ),
                ),
                ("data_emitere", models.DateField()),
                ("data_expirare", models.DateField(blank=True, null=True)),
                ("fisier", models.FileField(blank=True, upload_to="documente/")),
                ("observatii", models.TextField(blank=True)),
                (
                    "angajat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="angajati.angajat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documente",
                "ordering": ["data_expirare"],
            },
        ),
    ]
