# Generated by Django 5.2.10 on 2026-03-10 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clienti", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Oferta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numar", models.CharField(max_length=50, unique=True)),
                ("descriere", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("trimisa", "Trimisă"),
                            ("acceptata", "Acceptată"),
                            ("refuzata", "Refuzată"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("data_oferta", models.DateField(auto_now_add=True)),
                (
                    "valoare",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("valabila_pana", models.DateField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clienti.client"
                    ),
                ),
            ],
            options={
                "verbose_name": "Oferta",
                "verbose_name_plural": "Oferte",
                "ordering": ["-data_oferta"],
            },
        ),
    ]
