# Generated by Django 5.2.10 on 2026-03-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nume", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefon", models.CharField(blank=True, max_length=20)),
                ("adresa", models.TextField(blank=True)),
                (
                    "cui",
                    models.CharField(blank=True, max_length=20, verbose_name="CUI"),
                ),
                ("activ", models.BooleanField(default=True)),
                ("creat_la", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clienti",
                "ordering": ["nume"],
            },
        ),
    ]
