# Generated by Django 5.2.10 on 2026-03-10 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clienti", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comanda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numar", models.CharField(max_length=50, unique=True)),
                ("descriere", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("noua", "Nouă"),
                            ("in_lucru", "În lucru"),
                            ("finalizata", "Finalizată"),
                            ("anulata", "Anulată"),
                        ],
                        default="noua",
                        max_length=20,
                    ),
                ),
                ("data_comanda", models.DateField(auto_now_add=True)),
                ("data_livrare", models.DateField(blank=True, null=True)),
                (
                    "valoare",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clienti.client"
                    ),
                ),
            ],
            options={
                "verbose_name": "Comanda",
                "verbose_name_plural": "Comenzi",
                "ordering": ["-data_comanda"],
            },
        ),
    ]
